project_id = "ktxxhtubcffpqqievkgc"

[functions.game-import]
verify_jwt = false

[functions.bgg-import]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.send-message]
verify_jwt = false
